check if manifest file was downloaded correctly
Change-Id: Ide7f5a79b45c7b880e5615b7ba0c277a4d092389
Signed-off-by: Stephane Desneux <stephane.desneux@open.eurogiciel.org>

diff --git a/update_project b/update_project
--- a/update_project
+++ b/update_project
@@ -166,6 +166,11 @@ for PROJECT in ${PROJECT_LIST}; do
       MANIFEST_FILE=${LOCAL_MANIFEST_FILE}
     fi
 
+	if [[ ! -f "$MANIFEST_FILE" ]]; then
+		echo "Downloading manifest $MANIFEST failed."
+		exit 1
+	fi
+
     echo
 
     # check manifest file
